apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxapp-deployment
  labels:
    app: nginxapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginxapp
  template:
    metadata:
      labels:
        app: nginxapp
    spec:
      containers:
      - name: nginxserver
        image: lalitjoshi/nginx:alpine
        ports:
        - containerPort: 80
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
spec:
  selector:
    app: nodeapp 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8088
    targetPort: 80
    nodePort: 31110
